.travis.yml, README.md
Thanks to [KeithYokoma's comment](http://qiita.com/chiastolite/items/4f36039fdd7ea1a5a86f#comment-aff31c3ace5acdbd9d40), it can be shorter using [`execute(String[], File)`](http://docs.groovy-lang.org/latest/html/groovy-jdk/java/util/List.html#execute(java.lang.String[], java.io.File)) method.
=> README.md - rev-parse command can be shorter

README.md, build.gradle, example/build.gradle, example/gradle.properties.sample, src/main/groovy/com/deploygate/gradle/plugins/entities/DeployTarget.groovy, src/main/groovy/com/deploygate/gradle/plugins/tasks/LoginTask.groovy, src/main/groovy/com/deploygate/gradle/plugins/tasks/UploadTask.groovy
It turns out `Desktop.isDesktopSupported()` returns true on Circle CI and it tries to start a browser.
To prevent this behaviour, we should check environment variables in addition to the function currently used.
=> Stricter check for headless

README.md, example/build.gradle
"Cannot cast" error message appears when I compiled [this project's example](https://github.com/DeployGate/gradle-deploygate-plugin/tree/master/example). 
I think it's because `sourceFile` is defined as `File`, but it is used as a `String`.
https://github.com/DeployGate/gradle-deploygate-plugin/blob/master/src/main/groovy/com/deploygate/gradle/plugins/entities/DeployTarget.groovy#L8
=> Fix Readme and build.gradle file of example

README.md, example/build.gradle, src/main/groovy/com/deploygate/gradle/plugins/DeployGate.groovy, src/main/groovy/com/deploygate/gradle/plugins/entities/DeployTarget.groovy, src/test/groovy/com/deploygate/gradle/plugins/DeployTargetTest.groovy
Property `noAssemble` is true, Remove dependency of assemble task from uploadDeployGate task.
=> Supported noAssemble option

build.gradle, src/main/groovy/com/deploygate/gradle/plugins/DeployGate.groovy, src/main/groovy/com/deploygate/gradle/plugins/entities/DeployTarget.groovy, src/main/groovy/com/deploygate/gradle/plugins/tasks/UploadTask.groovy, src/test/groovy/com/deploygate/gradle/plugins/DeployTargetTest.groovy
This changeset fixes the problem that first app upload is *always* failing with Personal Free plan, which is default plan for new users.
=> Don't specify default visibility to upload

README.md, build.gradle, src/main/groovy/com/deploygate/gradle/plugins/Config.groovy, src/main/groovy/com/deploygate/gradle/plugins/DeployGate.groovy, src/main/groovy/com/deploygate/gradle/plugins/tasks/UploadTask.groovy
Trial implementation of retrieving APK file location from VariantScope, which is internal API of Gradle Android Plugin.
The behavior might be changed in future release of the plugin so it is encapsulated within a try-catch.
=> Retrieve APK file location from variant scope

README.md, build.gradle, src/main/groovy/com/deploygate/gradle/plugins/Config.groovy, src/main/groovy/com/deploygate/gradle/plugins/DeployGate.groovy
Retrieve task name from `variant`, instead of `output`.
=> Fix producing corrupted task names for flavors

src/main/groovy/com/deploygate/gradle/plugins/tasks/factory/AGPBasedUploadApkTaskFactory.groovy, src/test/acceptance/com/deploygate/gradle/plugins/AcceptanceKtsTestSpec.groovy, src/test/acceptance/com/deploygate/gradle/plugins/AcceptanceTestBaseSpec.groovy, src/test/acceptance/com/deploygate/gradle/plugins/AcceptanceTestSpec.groovy, src/test/acceptance/com/deploygate/gradle/plugins/internal/agp/AndroidGradlePluginAcceptanceSpec.groovy, src/test/acceptance/com/deploygate/gradle/plugins/internal/gradle/GradleCompatAcceptanceSpec.groovy
Fixed #86 
Android Gradle Plugin 3.5 (and later probably) won't configure unused package applications. If skipAssemble is true, DeployGate plugin cannot receive a configuration event from the provider so this issue has happened. Otherwise, assemble tasks will do it surely.
=> Evaluate a package application provider immediately if skipAssemble is true

build.gradle, src/main/groovy/com/deploygate/gradle/plugins/artifacts/PackageAppTaskCompat.groovy, src/main/groovy/com/deploygate/gradle/plugins/internal/agp/AndroidGradlePlugin.groovy, src/test/acceptance/com/deploygate/gradle/plugins/AcceptanceKtsTestSpec.groovy, src/test/acceptance/com/deploygate/gradle/plugins/AcceptanceTestSpec.groovy
AndroidStudio 3.6.0's breaking changes
- PackageApplication#outputDirectory has become Provider-based API
- PackageApplicaiton#signingConfig has become Provider-based API
The change summary of this PR
- Added a test case that verifies AndroidStudio 3.6.0-rc01
Notes
- The current HEAD works fine with 3.6.0-beta01 to beta05 but no need to have testcases for acceptance testing because they are *beta*.
=> Support AndroidStudio rc01

.circleci/config.yml, build.gradle, run_acceptance_tests.bash, src/main/groovy/com/deploygate/gradle/plugins/artifacts/PackageAppTaskCompat.groovy, src/main/groovy/com/deploygate/gradle/plugins/internal/VersionString.groovy, src/main/groovy/com/deploygate/gradle/plugins/internal/agp/AndroidGradlePlugin.groovy, src/test/groovy/com/deploygate/gradle/plugins/internal/VersionStringSpec.groovy, src/test/groovy/com/deploygate/gradle/plugins/internal/agp/AndroidGradlePluginSpec.groovy, src/test/unrollAcceptance/com/deploygate/gradle/plugins/internal/agp/AndroidGradlePluginAcceptanceSpec.groovy
SigningConfigData has been introduced since alpha14, and `signingConfig` has been deleted instead.
=> Fixed AndroidGradlePlugin 4.2.0-alpha14 made breaking changes around PackageApplication#signingConfig

.circleci/config.yml, src/main/groovy/com/deploygate/gradle/plugins/tasks/LoginTask.groovy, src/main/groovy/com/deploygate/gradle/plugins/tasks/UploadArtifactTask.groovy, src/test/unrollAcceptance/com/deploygate/gradle/plugins/internal/gradle/GradleCompatAcceptanceSpec.groovy
Starting from Gradle 7.0, we need to explicitly annotate the properties with `@Input`, `@Output` or `@Internal`. Also only one getter method is allowed for a property whereas Groovy generates 2 getters (`isXXX()` and `getXXX()`) for boolean property.
This pull request adds annotations (`LoginTask` and `UploadArtifactTask` properties are not for inputs or outputs so I annotated with `@Internal`) and suppress generating `getXXX()` for boolean property by having `isXXX()` method explicitly.
see also:
1. Missing annotation: https://docs.gradle.org/7.0/userguide/validation_problems.html#missing_annotation
2. Redundant getters: https://docs.gradle.org/7.0/userguide/validation_problems.html#redundant_getters
=> Compatibility with Gradle 7.0

build.gradle
Set Java7 as target (to be reverted) and use a proper variable to chose Groovy 3 dependencies.
=> Fix the target Java version and Groovy version matrix

.github/actions/setup-java/action.yml
This PR allows to set up Java11 before configuring Android SDK
=> SDKManager requires Java 11 or higher

src/main/groovy/com/deploygate/gradle/plugins/DeployGatePlugin.groovy, src/main/groovy/com/deploygate/gradle/plugins/dsl/DeployGateExtension.groovy, src/main/groovy/com/deploygate/gradle/plugins/internal/http/ApiClient.java, src/main/groovy/com/deploygate/gradle/plugins/tasks/UploadArtifactTask.groovy
Related to #147 and #148
As for buildFinished, we have not used this action for a while. We can safely delete this.
=> Remove the legacy Gradle build lifecycle API

.github/workflows/build-and-test.yml, build.gradle, src/test/unrollAcceptance/com/deploygate/gradle/plugins/internal/gradle/GradleCompatAcceptanceSpec.groovy
We have to chose the proper test cases depending on JRE versions because JDK17 cannot execute Gradle <7.3.
=> Add Gradle 8.x and Flamingo tests

src/main/groovy/com/deploygate/gradle/plugins/internal/http/HttpClient.java, src/main/groovy/com/deploygate/gradle/plugins/tasks/LoginTask.java, src/test/groovy/com/deploygate/gradle/plugins/tasks/LoginTaskSpec.groovy
Close #171
Don't allow a situation that an app owner name is not available but an api token is provided. 
This includes a bug fix related to a response file.
=> Builds would fail if api token is found but app owner name is not found

.github/workflows/release.yml
- Checkout `master` for spotless
- Use 2-digits after alpha/rc
- Don't specify jre version because it's fully handled in actions
Never mind the EOL by the way.
=> Fix a release workflow

.github/workflows/release.yml
The release workflow also execute testing codes so `app` service is required.
https://github.com/DeployGate/gradle-deploygate-plugin/actions/runs/4444135545/jobs/7802058573
=> Launch the app mock server in the release workflow

.github/dependabot.yml
Reduce # of opened PRs by dependabot.
- Limit # of PRs for gradle
- Group updates for GitHub Actions
=> dependabot seems to be fired up too much.

.github/workflows/build-and-test.yml
Fix https://github.com/DeployGate/gradle-deploygate-plugin/actions/runs/8228856588
=> Prevent using same names for different artifacts in a workflow run

.github/workflows/release.yml
These changes as same as [this pull request at deploygate-android-sdk](https://github.com/DeployGate/deploygate-android-sdk/pull/91)
-----
According to [the notice from sonatype](https://central.sonatype.org/news/20240617_migration_of_accounts/#the-impact-on-ossrh-and-the-central-publisher-portal), we cannot use username and password when uploading artifacts to the repository.
So, we should use a user token in our GitHub Actions workflow.
Ref. https://central.sonatype.org/news/20240617_migration_of_accounts/#the-impact-on-ossrh-and-the-central-publisher-portal
=> Fix: use sonatype user token for uploading artifacts

src/test/groovy/com/deploygate/gradle/plugins/TestSystemEnv.groovy
Environment variables were purged due to mock implementation so that HttpClient cannot look up required values.
=> Env stub class for testing is broken

.github/workflows/release.yml
I made the mistake of using an incorrect secret value when releasing an artifact.
=> fix: use correct value for access to Nexus Repository Manager
